In [ ]:
import os
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.tokenize import word_tokenize 
import numpy as np
import pandas as pd 
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.utils import compute_class_weight

In [ ]:
pip install nltk

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
df = pd.read_csv('/content/drive/MyDrive/ASOC-2022/tamil_sentiment_full_train.tsv',sep='\t')
df1 = pd.read_csv('/content/drive/MyDrive/ASOC-2022/tamil_sentiment_full_dev.tsv',sep='\t')

In [ ]:
df

In [ ]:
import joblib

In [ ]:
x_train = joblib.load('/content/drive/MyDrive/dataset1.joblib')

In [ ]:
type(df2)

numpy.ndarray

In [ ]:
type(df2)

numpy.ndarray

In [ ]:
len(df2)

33989

In [ ]:
def lower_X(text):
    if(type(text)==str):
        s = ''
        for i in text:
            try:
                s = s+ i.lower()
            except:
                s = s +i
        return s
    else:
        return 'None'

In [ ]:
df.head()

In [ ]:
df['Text'] = df['text'].map(lower_X)
df1['Text'] = df1['text'].map(lower_X)

In [ ]:
df['category'].value_counts()
# df['category'].isnull().sum()

Positive          20069
unknown_state      5628
Negative           4271
Mixed_feelings     4020
not-Tamil          1667
Positive              1
Name: category, dtype: int64

In [ ]:
df['category'].unique(),df.shape

(array(['unknown_state', 'Positive', 'Negative', 'Mixed_feelings',
        'not-Tamil', 'Positive '], dtype=object), (35656, 3))

In [ ]:
test = df1

In [ ]:
df = df[df['category']!='not-Tamil']
test = test[test['category']!='not-Tamil']

In [ ]:
len(df)

33989

In [ ]:
feel_dict = dict(zip(df['category'].unique(),np.arange(0,5)))
feel_dict

{'Mixed_feelings': 3,
 'Negative': 2,
 'Positive': 1,
 'Positive ': 4,
 'unknown_state': 0}

In [ ]:
feel_dict = {'Mixed_feelings': 3,
 'Negative': 2,
 'Positive': 1,
 'Positive ': 1,
 'unknown_state': 0}

In [ ]:
df['num_cat'] = df['category'].map(feel_dict)
test['num_cat'] = test['category'].map(feel_dict)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [ ]:
x = df['Text'].values
y = df['num_cat'].values

In [ ]:
x_test = test['Text']
y_train=df['num_cat']
y_test = test['num_cat'].values

In [ ]:
y_train

In [ ]:
import gensim

In [ ]:
import nltk

In [ ]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
nltk.download('popular')

In [ ]:
sentences = [word_tokenize(words) for words in df['Text'].values]

In [ ]:
from gensim.models import Word2Vec

In [ ]:
model = Word2Vec(sentences = sentences , size = 10, window = 5 , min_count = 1 , workers = 4)

In [ ]:
from nltk.tokenize import word_tokenize
import joblib
import gensim
import numpy as np

class Tokenizer:
    def __init__(self):
        self.word2vec = model
        self.mx = 154
    
    def pad_sentences(self, sent_array:np.array):
        mat = np.zeros((self.mx,10))
        for i in range(len(sent_array)):
            mat[i] = sent_array[i]
        return np.array([mat])
    
    def tokenize(self,texts:list):
        dataset = None
        for text in texts:
            sentence = word_tokenize(text)
            vector = []
            for words in sentence:
                try:
                    vector.append(self.word2vec.wv[words])
                except:
                    pass
            result = self.pad_sentences(vector)
            try:
                dataset = np.append(dataset,result,axis=0)
            except:
                dataset = result
        return dataset


In [ ]:
x_list = list(df['Text'].values)

In [ ]:
tokenizer = Tokenizer()
x_train = tokenizer.tokenize(x_list)

In [ ]:
joblib.dump(x_train , '/content/drive/MyDrive/dataset1.joblib')

['/content/drive/MyDrive/dataset1.joblib']

In [ ]:
x_train = joblib.load('/content/drive/MyDrive/dataset1.joblib')

In [ ]:
x_train

In [ ]:
x_train

In [ ]:
y_list = list(test['Text']) 

In [ ]:
y_list

In [ ]:
tokenizer = Tokenizer()
x_test = tokenizer.tokenize(y_list)

In [ ]:
x_test

In [ ]:
pip install tensorflow

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Input,Flatten,Dropout

In [ ]:
model1 = Sequential()

In [ ]:
model1.add(Input(shape=(154,10)))
model1.add(Dense(100,activation = 'relu'))
model1.add(Dense(70, activation = 'relu'))
# model1.add(Dropout(0.5))
model1.add(Dense(50,activation = 'relu'))
# model1.add(Dropout(0.5))
model1.add(Dense(25,activation = 'relu'))
# model1.add(Dropout(0.5))
model1.add(Flatten())
model1.add(Dense(4,activation='softmax'))

In [ ]:
model1.compile(optimizer = 'adam' , loss = 'categorical_crossentropy' ,metrics = ['accuracy'])

In [ ]:
df2.shape

NameError: ignored

In [ ]:
df2

In [ ]:
y.shape

(33989,)

In [ ]:
y

array([0, 1, 1, ..., 2, 1, 1])

In [ ]:
x_test.shape

(3786, 154, 10)

In [ ]:
x_test

In [ ]:
y_test.shape

(3786,)

In [ ]:
y_test

array([0, 1, 1, ..., 3, 1, 1])

In [ ]:
from tensorflow.keras.utils import to_categorical

In [ ]:
y = to_categorical(y)

In [ ]:
y_test1 = to_categorical(y_test)

In [ ]:
y_test1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       ...,
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.]], dtype=float32)

In [ ]:
model1.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 154, 100)          1100      
                                                                 
 dense_1 (Dense)             (None, 154, 50)           5050      
                                                                 
 dense_2 (Dense)             (None, 154, 25)           1275      
                                                                 
 flatten (Flatten)           (None, 3850)              0         
                                                                 
 dense_3 (Dense)             (None, 4)                 15404     
                                                                 
Total params: 22,829
Trainable params: 22,829
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model1.fit(x_train , y , validation_data = (x_test , y_test1) , batch_size =128 , epochs = 600)

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report


In [ ]:
p = model1.predict(x_test)

In [ ]:
pred = [np.argmax(i) for i in p]

In [ ]:
pred

In [ ]:
y_test

array([0, 1, 1, ..., 3, 1, 1])

In [ ]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       611
           1       0.60      1.00      0.75      2257
           2       0.00      0.00      0.00       480
           3       0.00      0.00      0.00       438

    accuracy                           0.60      3786
   macro avg       0.15      0.25      0.19      3786
weighted avg       0.36      0.60      0.45      3786



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
